project:
  type: book
  output-dir: docs
  

book:
  title: "Data Mining 2026"
  author: "Camille Signoretto"
  date: "Février-juin 2026"
  subtitle: "Master Meci - Parcours PISE et CCESE - Option Data"
  language: fr 
  search: true
  repo-url: https://github.com/Camille-Sisi/Data-Mining-2026
  sidebar: 
    style: docked
  chapters:
    - index.qmd
    - part: "Séance 1"
      chapters:
      - 01-Base-de-donnees.qmd
      # - 02-Manipulation-base.qmd
      # - 03-Manipulation-variables.qmd
      # - 04-Récapitulatif.qmd

format:
  bookup-html:
    toc: true
    toc-title: "Sur cette page"
    toc-depth: 3
    
    