
```{r setup, include = FALSE, cache = FALSE}
library(knitr)
library(tidyverse)

knitr::opts_chunk$set(cache = TRUE,
                      echo = TRUE,
                      comment = "")

```

# Présentation {.unnumbered}

## À propos de ce document {.unnumbered}

Ce document est la version 2026 du cours de Data Mining dispensé aux étudiants de deuxième année de l’option Data du master MECI parcours PISE et CCESE. Ce cours est partagé avec [Claude Grasland](https://github.com/ClaudeGrasland).

Ce document est régulièrement corrigé et mis à jour. La version de référence est disponible en ligne à l’adresse suivante :

-   <https://github.com/Camille-Sisi/Data-Mining-2026>.

Pour toute suggestion ou correction, n'hésitez pas à me contacter [par mail](mailto:camille.signoretto@u-paris.fr).

## Prérequis {.unnumbered}

Le seul prérequis pour suivre ce document est d'avoir installé R et RStudio sur votre ordinateur. Il s'agit de deux logiciels libres, gratuits, téléchargeables en ligne et fonctionnant sous PC, Mac et Linux.

Pour installer R, il suffit de se rendre sur une des pages suivantes[^1]:

-   [Installer R sous Windows](https://cloud.r-project.org/bin/windows/base/)
-   [Installer R sous Mac](https://cloud.r-project.org/bin/macosx/)

Pour installer RStudio, rendez-vous sur la page suivante et téléchargez la version adaptée à votre système :

-   <https://www.rstudio.com/products/rstudio/download/#download>

## Licence {.unnumbered}

Ce document est mis à disposition selon les termes de la [Licence Creative Commons Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 4.0 International](http://creativecommons.org/licenses/by-nc-sa/4.0/).


[^1]: Sous Linux, utilisez votre gestionnaire de packages habituel.